### GET Products

GET http://localhost:5000/api/products

### POST Products

POST http://localhost:5000/api/products
Content-Type: application/json

{
      "title": "Goma de borrar",
    "description": "Goma de borrar blanca para lápiz",
    "code": "GOM303",
    "price": 50.00,
    "status": true,
    "stock": 300,
    "category": "Escritura"
}